### ISSUE TITLE
Code Review "Sluzby"

### ISSUE THREAD

**Issue by OksanaMir** [BaraKalvo/PROJEKT-Sluzby#1]
Ahoj, 
omlouvam se za diakritiku :)
#### 1. Rozestupy mezi sekci

 - Delas rozestopy pomoci marginu na potomkach. Melo bu byt uplne jinak. 
 - [x] Na obal sekci pridej padding na ose X. Bude to rozestup od hranic ramecku kontejneru do granic ramecku sekci a bude platit pro vsechny velikosti obrazovek pokud nedosahne max-width. Od max-width zacnou fungovat levy a pravy marginy 'auto' na kontentu 
 - [x] Odstran margin na ose Y 60px na potomkach a naopak pridej ho seksim. Od *640px* na **.uvod**  a **.kancelar** nastav margin-bottom 80px

```css
        /* hned po body */
    .kontejner {
        padding-inline: 20px; /* pokud je ten padding, memusis na potomky pridavar margin 20px(.obsah2,.obsah3, .box)*/
    }
    section {
        margin-block: 60px;
    }

    /* .cestovatel {
        margin-top: 60px;
    } */

     .tlac2odsazeni {
    ...
    /* margin-bottom: 60px; */
    }
    .obsah1,/*nahradit v CSS a HTML za obsah*/
    .obsah2,
    .obsah3 {
        margin: 30px auto;
    }
    .box{
        ...
        padding: 20px;
        margin-block: 15px;
    }
    /* .box:last-child {
        margin-bottom: 60px;
    } */

    @media screen and (min-width: 640px) {
        .uvod,
        .kancelar {
            margin-bottom: 80px;
        }
        /* .tlacitko1,
            .tlacitko2 {
                margin-bottom: 80px;
        } */
            /* .delegatiramecky {
            margin-bottom: 60px;
        } */
        /* .obsah2,
        .obsah3 {
            margin-bottom: 40px;
        } */

    }
    @media screen and (min-width: 1100px) {
        .uvod {
            ...
            /* margin-top: 60px; */
            /* margin-bottom: 80px; */
        } 
        .kancelar,
        .delegati {
            /* margin-bottom: 80px; */
        }
        .tlac2odsazeni {
        ...
        /* margin-bottom: 60px; */}
        /* .delegatitext {
            margin-right: 60px;
            } */
    }
```

#### 2. Flexboxy

 - Prvky s tridami .uvodtext a .uvodobrazek slo by nastilovat i trochu jinak. misto order na potomku nastavit flex-direction: row-reverse; na rodici.

```css
    .uvod {
        ...
        text-align: left;
        flex-direction: row-reverse;
    }
    .uvodtext,
	.uvodobrazek {
        flex: 0 0 calc((100% - 60px) / 2);
    }
```

 - Zace rozestup se snazis udelat pomoci margina. Pro flexbox tady by bylo fajn poizit moznosti samotneho flexboxa

```css
    .box img {
        padding-right: 30px;
    }
    .box p {
	/* padding: 30px 20px 30px 0; dela to rodicovske align-items: center; */
	/* margin: 0; */
    }
    .tlac1odsazeni,
    .tlac2odsazeni {
        margin-block: 10px;
    }
    /* .tlac2odsazeni {
        margin-top: 10px; 
        margin-bottom: 60px;
    } */

   

    @media screen and (min-width: 640px) {
        .obsah {
            max-width: 550px;
        }
        .dvetlacitka {
            align-items: center; /*vycentruje potomky po ose Y*/
        }

        .tlac1odsazeni {
            margin-block: 0;
        }

        .tlac2odsazeni {
           	margin-left: 20px;
            margin-block: 0;
        }
        .kancelarramecky,
        .delegatiramecky {
            width: 100%;/*definujeme sirku flex-kintejnery. Bude dedit od rodice.*/
        }
    /* ----box---- */
    .box {
        /* margin: 0 20px 0 0; */
        flex: 0 0 calc((100% - 60px) / 3);/*misto nastaveni marginu*/

    }
    .box:last-child {
        /* margin: 0; */
    }

    }

    @media screen and (min-width: 1100px) {
        .kancelar,
        .delegati {
            ..
            width: 100%;/*definujeme sirku flex-kintejnery. Bude dedit od rodice.*/
            justify-content: space-between;
        }
    }
    .kancelartext {
        order: 1;
        /* margin-left: 60px; */
    }
    .kancelartext,
    .delegatitext {
        flex: 0 0 430px;/*Zakazat rust*/
        text-align: left;
    }

```
Neni tady vsechno.
